export const DEFAULT_MENUS = [
  {
    id: 'menu_001',
    parent_id: null,
    name: 'Dashboard',
    module: 'dashboard',
    text: 'Dashboard Overview',
    link: '/dashboard',
    active: true,
    seq: 1,
    icon: 'Odometer',
    children: [
      {
        id: 'menu_002',
        parent_id: 'menu_001',
        name: 'Overview',
        module: 'dashboard',
        text: 'Dashboard Overview',
        link: '/dashboard/overview',
        active: true,
        seq: 1,
        icon: 'DataLine'
      },
      {
        id: 'menu_003',
        parent_id: 'menu_001',
        name: 'Statistics',
        module: 'dashboard',
        text: 'Dashboard Statistics',
        link: '/dashboard/statistics',
        active: true,
        seq: 2,
        icon: 'TrendCharts'
      },
      {
        id: 'menu_010',
        parent_id: 'menu_001',
        name: 'Real-time Data',
        module: 'dashboard',
        text: 'Real-time Data',
        link: '/dashboard/realtime',
        active: true,
        seq: 3,
        icon: 'Monitor'
      },
      {
        id: 'menu_011',
        parent_id: 'menu_001',
        name: 'Performance',
        module: 'dashboard',
        text: 'Performance Metrics',
        link: '/dashboard/performance',
        active: true,
        seq: 4,
        icon: 'Cpu'
      }
    ]
  },
  {
    id: 'menu_026',
    parent_id: null,
    name: 'Function Unit',
    module: 'unit',
    text: 'Function Unit',
    link: '/unit',
    active: true,
    seq: 2,
    icon: 'Grid',
    children: [
      {
        id: 'menu_027',
        parent_id: 'menu_026',
        name: 'Form Design',
        module: 'unit',
        text: 'Form Design',
        link: '/unit/form-design',
        active: true,
        seq: 1,
        icon: 'EditPen'
      },
      {
        id: 'menu_028',
        parent_id: 'menu_026',
        name: 'Staff Management',
        module: 'unit',
        text: 'Staff Management',
        link: '/unit/staff-management',
        active: true,
        seq: 2,
        icon: 'User'
      }
    ]
  },
  {
    id: 'menu_004',
    parent_id: null,
    name: 'System',
    module: 'system',
    text: 'System Management',
    link: '/system',
    active: true,
    seq: 2,
    icon: 'Setting',
    children: [
      {
        id: 'menu_005',
        parent_id: 'menu_004',
        name: 'User Management',
        module: 'system',
        text: 'User Management',
        link: '/system/users',
        active: true,
        seq: 1,
        icon: 'User'
      },
      {
        id: 'menu_006',
        parent_id: 'menu_004',
        name: 'Role Management',
        module: 'system',
        text: 'Role Management',
        link: '/system/roles',
        active: true,
        seq: 2,
        icon: 'UserFilled'
      },
      {
        id: 'menu_012',
        parent_id: 'menu_004',
        name: 'Permission Management',
        module: 'system',
        text: 'Permission Management',
        link: '/system/permissions',
        active: true,
        seq: 3,
        icon: 'Key'
      },
      {
        id: 'menu_013',
        parent_id: 'menu_004',
        name: 'Audit Logs',
        module: 'system',
        text: 'Audit Logs',
        link: '/system/logs',
        active: true,
        seq: 4,
        icon: 'Document'
      },
      {
        id: 'menu_014',
        parent_id: 'menu_004',
        name: 'System Configuration',
        module: 'system',
        text: 'System Configuration',
        link: '/system/config',
        active: true,
        seq: 5,
        icon: 'Cog'
      }
    ]
  },
  {
    id: 'menu_007',
    parent_id: null,
    name: 'Settings',
    module: 'settings',
    text: 'Settings',
    link: '/settings',
    active: true,
    seq: 3,
    icon: 'Tools',
    children: [
      {
        id: 'menu_008',
        parent_id: 'menu_007',
        name: 'General',
        module: 'settings',
        text: 'General Settings',
        link: '/settings/general',
        active: true,
        seq: 1,
        icon: 'Operation'
      },
      {
        id: 'menu_009',
        parent_id: 'menu_007',
        name: 'Security',
        module: 'settings',
        text: 'Security Settings',
        link: '/settings/security',
        active: true,
        seq: 2,
        icon: 'Lock'
      },
      {
        id: 'menu_015',
        parent_id: 'menu_007',
        name: 'Notification',
        module: 'settings',
        text: 'Notification Settings',
        link: '/settings/notification',
        active: true,
        seq: 3,
        icon: 'Bell'
      },
      {
        id: 'menu_016',
        parent_id: 'menu_007',
        name: 'Appearance',
        module: 'settings',
        text: 'Appearance Settings',
        link: '/settings/appearance',
        active: true,
        seq: 4,
        icon: 'Palette'
      },
      {
        id: 'menu_017',
        parent_id: 'menu_007',
        name: 'Language',
        module: 'settings',
        text: 'Language Settings',
        link: '/settings/language',
        active: true,
        seq: 5,
        icon: 'Connection'
      }
    ]
  },
  {
    id: 'menu_018',
    parent_id: null,
    name: 'Content',
    module: 'content',
    text: 'Content Management',
    link: '/content',
    active: true,
    seq: 4,
    icon: 'DocumentCopy',
    children: [
      {
        id: 'menu_019',
        parent_id: 'menu_018',
        name: 'Articles',
        module: 'content',
        text: 'Article Management',
        link: '/content/articles',
        active: true,
        seq: 1,
        icon: 'EditPen'
      },
      {
        id: 'menu_020',
        parent_id: 'menu_018',
        name: 'Categories',
        module: 'content',
        text: 'Category Management',
        link: '/content/categories',
        active: true,
        seq: 2,
        icon: 'Folder'
      },
      {
        id: 'menu_021',
        parent_id: 'menu_018',
        name: 'Media Library',
        module: 'content',
        text: 'Media Library',
        link: '/content/media',
        active: true,
        seq: 3,
        icon: 'PictureFilled'
      }
    ]
  },
  {
    id: 'menu_022',
    parent_id: null,
    name: 'Reports',
    module: 'reports',
    text: 'Reports & Analytics',
    link: '/reports',
    active: true,
    seq: 5,
    icon: 'DataAnalysis',
    children: [
      {
        id: 'menu_023',
        parent_id: 'menu_022',
        name: 'Sales Reports',
        module: 'reports',
        text: 'Sales Reports',
        link: '/reports/sales',
        active: true,
        seq: 1,
        icon: 'TrendCharts'
      },
      {
        id: 'menu_024',
        parent_id: 'menu_022',
        name: 'User Reports',
        module: 'reports',
        text: 'User Reports',
        link: '/reports/users',
        active: true,
        seq: 2,
        icon: 'User'
      },
      {
        id: 'menu_025',
        parent_id: 'menu_022',
        name: 'Custom Reports',
        module: 'reports',
        text: 'Custom Reports',
        link: '/reports/custom',
        active: true,
        seq: 3,
        icon: 'Document'
      }
    ]
  }
]

export const DEFAULT_MODULES = [
  {
    id: 'module_001',
    name: 'User Management',
    category: 'portal',
    version: '1.0.0',
    file: 'user-management.js',
    type: 1,
    tab: 'portal',
    entry: false,
    created_at: '2024-01-01 10:00:00',
    created_by: 'admin',
    updated_at: '2024-01-01 10:00:00',
    updated_by: 'admin'
  },
  {
    id: 'module_002',
    name: 'Statistics',
    category: 'portal',
    version: '1.2.0',
    file: 'statistics.js',
    type: 2,
    tab: 'portal',
    entry: false,
    created_at: '2024-01-02 14:30:00',
    created_by: 'admin',
    updated_at: '2024-01-05 09:15:00',
    updated_by: 'admin'
  },
  {
    id: 'module_003',
    name: 'System Configuration',
    category: 'admin_center',
    version: '2.0.0',
    file: 'system-config.js',
    type: 1,
    tab: 'admin_center',
    entry: true,
    created_at: '2024-01-03 11:20:00',
    created_by: 'admin',
    updated_at: '2024-01-10 16:45:00',
    updated_by: 'admin'
  },
  {
    id: 'module_004',
    name: 'Permission Management',
    category: 'admin_center',
    version: '1.5.0',
    file: 'permission.js',
    type: 2,
    tab: 'admin_center',
    entry: false,
    created_at: '2024-01-04 08:00:00',
    created_by: 'admin',
    updated_at: '2024-01-08 13:20:00',
    updated_by: 'admin'
  },
  {
    id: 'module_005',
    name: 'Workstation',
    category: 'workstation',
    version: '1.0.0',
    file: 'workstation.js',
    type: 1,
    tab: 'workstation',
    entry: true,
    created_at: '2024-01-05 15:30:00',
    created_by: 'admin',
    updated_at: '2024-01-05 15:30:00',
    updated_by: 'admin'
  },
  {
    id: 'module_006',
    name: 'Utility Functions',
    category: 'workstation',
    version: '1.3.0',
    file: 'utils.js',
    type: 2,
    tab: 'workstation',
    entry: false,
    created_at: '2024-01-06 09:00:00',
    created_by: 'admin',
    updated_at: '2024-01-12 10:30:00',
    updated_by: 'admin'
  },
  {
    id: 'module_007',
    name: 'Dashboard',
    category: 'portal',
    version: '2.1.0',
    file: 'dashboard.js',
    type: 1,
    tab: 'portal',
    entry: true,
    created_at: '2024-01-07 14:00:00',
    created_by: 'admin',
    updated_at: '2024-01-15 11:30:00',
    updated_by: 'admin'
  },
  {
    id: 'module_008',
    name: 'Content Management',
    category: 'portal',
    version: '1.8.0',
    file: 'content-management.js',
    type: 1,
    tab: 'portal',
    entry: false,
    created_at: '2024-01-08 09:30:00',
    created_by: 'admin',
    updated_at: '2024-01-18 16:45:00',
    updated_by: 'admin'
  },
  {
    id: 'module_009',
    name: 'Media Library',
    category: 'portal',
    version: '1.5.2',
    file: 'media-library.js',
    type: 2,
    tab: 'portal',
    entry: false,
    created_at: '2024-01-09 11:00:00',
    created_by: 'admin',
    updated_at: '2024-01-20 13:20:00',
    updated_by: 'admin'
  },
  {
    id: 'module_010',
    name: 'Audit Logs',
    category: 'admin_center',
    version: '1.2.0',
    file: 'audit-logs.js',
    type: 1,
    tab: 'admin_center',
    entry: false,
    created_at: '2024-01-10 15:30:00',
    created_by: 'admin',
    updated_at: '2024-01-22 10:15:00',
    updated_by: 'admin'
  },
  {
    id: 'module_011',
    name: 'API Gateway',
    category: 'admin_center',
    version: '3.0.0',
    file: 'api-gateway.js',
    type: 2,
    tab: 'admin_center',
    entry: false,
    created_at: '2024-01-11 10:00:00',
    created_by: 'admin',
    updated_at: '2024-01-25 09:45:00',
    updated_by: 'admin'
  },
  {
    id: 'module_012',
    name: 'Notification Service',
    category: 'workstation',
    version: '1.7.0',
    file: 'notification-service.js',
    type: 1,
    tab: 'workstation',
    entry: false,
    created_at: '2024-01-12 14:30:00',
    created_by: 'admin',
    updated_at: '2024-01-28 16:20:00',
    updated_by: 'admin'
  },
  {
    id: 'module_013',
    name: 'Task Scheduler',
    category: 'workstation',
    version: '2.2.0',
    file: 'task-scheduler.js',
    type: 2,
    tab: 'workstation',
    entry: false,
    created_at: '2024-01-13 09:15:00',
    created_by: 'admin',
    updated_at: '2024-01-30 11:30:00',
    updated_by: 'admin'
  },
  {
    id: 'module_014',
    name: 'Cache Service',
    category: 'admin_center',
    version: '1.4.0',
    file: 'cache-service.js',
    type: 2,
    tab: 'admin_center',
    entry: false,
    created_at: '2024-01-14 13:45:00',
    created_by: 'admin',
    updated_at: '2024-02-02 14:50:00',
    updated_by: 'admin'
  },
  {
    id: 'module_015',
    name: 'Search Engine',
    category: 'portal',
    version: '2.5.0',
    file: 'search-engine.js',
    type: 1,
    tab: 'portal',
    entry: false,
    created_at: '2024-01-15 10:30:00',
    created_by: 'admin',
    updated_at: '2024-02-05 09:20:00',
    updated_by: 'admin'
  }
]

// Mock staff data
export const DEFAULT_STAFFS = [
  {
    staffId: 'STAFF_001',
    staffName: 'John Doe',
    email: 'john.doe@company.com',
    mobileTelNum: '13800138001',
    company: 'Main Company',
    department: 'IT',
    jobTitle: 'Software Engineer',
    entityManager: 'Alice Smith',
    entityManagerId: 'MANAGER_001',
    functionManager: 'Bob Johnson',
    functionManagerId: 'MANAGER_002'
  },
  {
    staffId: 'STAFF_002',
    staffName: 'Jane Smith',
    email: 'jane.smith@company.com',
    mobileTelNum: '13900139002',
    company: 'Main Company',
    department: 'HR',
    jobTitle: 'HR Specialist',
    entityManager: 'Charlie Brown',
    entityManagerId: 'MANAGER_003',
    functionManager: 'David Wilson',
    functionManagerId: 'MANAGER_004'
  },
  {
    staffId: 'STAFF_003',
    staffName: 'Mike Johnson',
    email: 'mike.johnson@company.com',
    mobileTelNum: '13700137003',
    company: 'Branch Company',
    department: 'Finance',
    jobTitle: 'Accountant',
    entityManager: 'Eve Davis',
    entityManagerId: 'MANAGER_005',
    functionManager: 'Frank Miller',
    functionManagerId: 'MANAGER_006'
  },
  {
    staffId: 'STAFF_004',
    staffName: 'Sarah Wilson',
    email: 'sarah.wilson@company.com',
    mobileTelNum: '13600136004',
    company: 'Main Company',
    department: 'Marketing',
    jobTitle: 'Marketing Manager',
    entityManager: 'Grace Taylor',
    entityManagerId: 'MANAGER_007',
    functionManager: 'Henry Anderson',
    functionManagerId: 'MANAGER_008'
  },
  {
    staffId: 'STAFF_005',
    staffName: 'Tom Davis',
    email: 'tom.davis@company.com',
    mobileTelNum: '13500135005',
    company: 'Branch Company',
    department: 'IT',
    jobTitle: 'System Administrator',
    entityManager: 'Ivy Martinez',
    entityManagerId: 'MANAGER_009',
    functionManager: 'Jack Garcia',
    functionManagerId: 'MANAGER_010'
  },
  {
    staffId: 'STAFF_006',
    staffName: 'Lisa Miller',
    email: 'lisa.miller@company.com',
    mobileTelNum: '13400134006',
    company: 'Main Company',
    department: 'Operations',
    jobTitle: 'Operations Coordinator',
    entityManager: 'Kevin Robinson',
    entityManagerId: 'MANAGER_011',
    functionManager: 'Laura Clark',
    functionManagerId: 'MANAGER_012'
  },
  {
    staffId: 'STAFF_007',
    staffName: 'James Taylor',
    email: 'james.taylor@company.com',
    mobileTelNum: '13300133007',
    company: 'Branch Company',
    department: 'Sales',
    jobTitle: 'Sales Representative',
    entityManager: 'Mark Rodriguez',
    entityManagerId: 'MANAGER_013',
    functionManager: 'Nancy Lewis',
    functionManagerId: 'MANAGER_014'
  },
  {
    staffId: 'STAFF_008',
    staffName: 'Mary Anderson',
    email: 'mary.anderson@company.com',
    mobileTelNum: '13200132008',
    company: 'Main Company',
    department: 'Legal',
    jobTitle: 'Legal Counsel',
    entityManager: 'Oscar Lee',
    entityManagerId: 'MANAGER_015',
    functionManager: 'Patricia Walker',
    functionManagerId: 'MANAGER_016'
  },
  {
    staffId: 'STAFF_009',
    staffName: 'Robert Martinez',
    email: 'robert.martinez@company.com',
    mobileTelNum: '13100131009',
    company: 'Branch Company',
    department: 'IT',
    jobTitle: 'DevOps Engineer',
    entityManager: 'Quinn Hill',
    entityManagerId: 'MANAGER_017',
    functionManager: 'Rachel Scott',
    functionManagerId: 'MANAGER_018'
  },
  {
    staffId: 'STAFF_010',
    staffName: 'Jennifer Garcia',
    email: 'jennifer.garcia@company.com',
    mobileTelNum: '13000130010',
    company: 'Main Company',
    department: 'Product',
    jobTitle: 'Product Manager',
    entityManager: 'Steve Green',
    entityManagerId: 'MANAGER_019',
    functionManager: 'Tracy Adams',
    functionManagerId: 'MANAGER_020'
  },
  {
    staffId: 'STAFF_011',
    staffName: 'William Robinson',
    email: 'william.robinson@company.com',
    mobileTelNum: '13800138011',
    company: 'Branch Company',
    department: 'Finance',
    jobTitle: 'Financial Analyst',
    entityManager: 'Ursula Baker',
    entityManagerId: 'MANAGER_021',
    functionManager: 'Victor Gonzalez',
    functionManagerId: 'MANAGER_022'
  },
  {
    staffId: 'STAFF_012',
    staffName: 'Elizabeth Lewis',
    email: 'elizabeth.lewis@company.com',
    mobileTelNum: '13900139012',
    company: 'Main Company',
    department: 'HR',
    jobTitle: 'Recruiter',
    entityManager: 'Wanda Nelson',
    entityManagerId: 'MANAGER_023',
    functionManager: 'Xavier Carter',
    functionManagerId: 'MANAGER_024'
  },
  {
    staffId: 'STAFF_013',
    staffName: 'David Lee',
    email: 'david.lee@company.com',
    mobileTelNum: '13700137013',
    company: 'Branch Company',
    department: 'IT',
    jobTitle: 'Frontend Developer',
    entityManager: 'Yvonne Mitchell',
    entityManagerId: 'MANAGER_025',
    functionManager: 'Zachary Perez',
    functionManagerId: 'MANAGER_026'
  },
  {
    staffId: 'STAFF_014',
    staffName: 'Barbara Hill',
    email: 'barbara.hill@company.com',
    mobileTelNum: '13600136014',
    company: 'Main Company',
    department: 'Marketing',
    jobTitle: 'Content Specialist',
    entityManager: 'Alan Roberts',
    entityManagerId: 'MANAGER_027',
    functionManager: 'Betty Turner',
    functionManagerId: 'MANAGER_028'
  },
  {
    staffId: 'STAFF_015',
    staffName: 'Richard Scott',
    email: 'richard.scott@company.com',
    mobileTelNum: '13500135015',
    company: 'Branch Company',
    department: 'Operations',
    jobTitle: 'Operations Manager',
    entityManager: 'Charles Phillips',
    entityManagerId: 'MANAGER_029',
    functionManager: 'Diana Campbell',
    functionManagerId: 'MANAGER_030'
  }
]
